<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Event\EventInterface;

/**
 * Mobile Controller
 *
 * @method \App\Model\Entity\Mobile[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class MobileController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function login()
    {
    }
    public function anos()
    {
        $this->LoadModel('Pits');
        $anos = $this->Pits->find('all')->toArray();

    }
    public function lista()
    {
    }
//    anos
//    login
//    valores
}
